spring:
  application:
    name: hrent-search
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 193.112.33.124:9300
server:
  port: 9002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
